### PR TITLE
Custom eV/Å force units in the GUI

### PR DESCRIPTION
**Pull request by jfrodlova**
I added eV/A force units. They are displayed correctly both in Units widget and in Geometry Optimization (see images).
However, I was not able to verify if the conversion to Newtons and other units works properly.
I will try to figure out how to set it as default later.

custom_eV_A_force_1
custom_eV_A_force_2

### CODE REVIEW

**Comment by ondracka** [comment]
This looks good. The functionality seems to work fine, at least the conversion from Ha/Bohr (the atomic force units) looks reasonable. I would maybe rename the commit to just something like "Add eV/Å force unit".

You can also add a  `Fixes ondracka/nomad#2` to the commit description, this way the corresponding issue will close automatically when this is merged. Other that that looks great. Congratulations on your first github PR.

**Comment by jfrodlova** [comment]
I changed the alias from "eV/Å" to "eV_Å" because it was throwing an error ("mismatching dimensions") and the commit message as you suggested.

Setting eV/Å as default still remains to be done. I tried changing the order of units in the file, but it is not that straightforward (it made no difference). Is it okay to handle the default units separately?

**Comment by ondracka** [comment]
OK, in that case it would be better to change it once more to force_eV_over_A and eV_over_Å, than we merge it...

**Comment by ondracka** [comment]
Regarding the default, lets just skip it for now and take a look at https://github.com/ondracka/nomad/issues/1

**Comment by jfrodlova** [comment]
Done.

**Comment by ondracka** [comment]
Thanks, merged.

**Pull request merged**
